# Jekyll configuration
url: https://norriz.github.io/
theme: minima
author: Norriz
title: Getting started with Jekyll

email: >-
description: There should be some awesome description. Not sure tho.

# user acc
github_username:  Norriz
linkedin_username:  something :)
