# Jekyll configuration
url: https://norriz.github.io/
theme: minima

title: Nora von Harten
email: >-
description: There should be some awesome description. Not sure tho.

# user acc
github_username:  Norriz
linkedin_username:  nora-vonharten
