# Jekyll configuration
url: https://norriz.github.io/
theme: minima

title: My Name, I guess?
email: >-
description: There should be some awesome description. Not sure tho.
 

github_username:  Norriz
linkedin_username:  nora-vonharten
