# Jekyll configuration
url: https://norriz.github.io/
theme: minima
author: Nora
title: Nora 

email: >-
description: There should be some awesome description. Not sure tho.

# user acc
github_username:  Norriz
linkedin_username:  nora-vonharten
