# Jekyll configuration
url: https://norriz.github.io/

plugins:
- jekyll-remote-theme
remote_theme: pages-themes/dinky@v0.2.0

name: Nora
author: Norriz
title: Coursera Course - my own webpage

email: >-
description: There should be some awesome description. Not sure tho.

# user acc
footer-links:
  github: Norriz
  linkedin_username:  something :)
