# Jekyll configuration
url: https://norriz.github.io/
theme: minima
author: Norriz
title: Coursera Course - my own webpage

email: >-
description: There should be some awesome description. Not sure tho.

# user acc
github_username:  Norriz
linkedin_username:  something :)
